import Link from 'next/link';
import { supabase } from '@/utils/supabase';
import { redirect } from 'next/navigation';

export default function RegisterPage() {
  
  // SERVER ACTION: Securely runs on the backend
  async function handleRegister(formData: FormData) {
    'use server';
    
    const name = formData.get('name') as string;
    const email = formData.get('email') as string;
    const password = formData.get('password') as string;

    // 1. Create the user in Supabase Auth (Securely handles the password)
    const { data: authData, error: authError } = await supabase.auth.signUp({
      email,
      password,
    });

    if (authError) {
      console.error('Registration failed:', authError.message);
      // In a production app, we would show this error on the UI.
      // For this prototype, we will log it to the VS Code terminal.
      return; 
    }

    // 2. If successful, link them to our public.users table!
    if (authData.user) {
      const { error: dbError } = await supabase.from('users').insert({
        user_id: authData.user.id, // Use the exact ID generated by Supabase Auth
        name: name,
        email: email,
        password_hash: 'managed_by_supabase_auth', // We no longer store real passwords!
        role: 'buyer' // Automatically assign them as a buyer
      });

      if (dbError) {
        console.error('Database linking failed:', dbError.message);
      }
    }

    // 3. Redirect the user to the login page after successful registration
    redirect('/login');
  }

  return (
    <main className="min-h-screen flex items-center justify-center p-8 bg-white text-black font-sans">
      
      <div className="w-full max-w-md border-4 border-black p-8 bg-white shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]">
        
        {/* Header */}
        <div className="mb-8 border-b-4 border-black pb-4 text-center">
          <h1 className="text-4xl font-extrabold uppercase tracking-widest mb-1">E-Store</h1>
          <p className="text-sm font-mono uppercase tracking-widest">Create an Account</p>
        </div>

        {/* Registration Form */}
        <form action={handleRegister} className="space-y-6">
          
          {/* Full Name */}
          <div className="flex flex-col">
            <label htmlFor="name" className="font-bold uppercase tracking-wider mb-2 text-sm">Full Name</label>
            <input 
              type="text" 
              id="name" 
              name="name" 
              required 
              placeholder="e.g. John Doe"
              className="border-2 border-black p-3 focus:outline-none focus:ring-2 focus:ring-black font-mono" 
            />
          </div>

          {/* Email */}
          <div className="flex flex-col">
            <label htmlFor="email" className="font-bold uppercase tracking-wider mb-2 text-sm">Email Address</label>
            <input 
              type="email" 
              id="email" 
              name="email" 
              required 
              placeholder="you@example.com"
              className="border-2 border-black p-3 focus:outline-none focus:ring-2 focus:ring-black font-mono" 
            />
          </div>

          {/* Password */}
          <div className="flex flex-col">
            <label htmlFor="password" className="font-bold uppercase tracking-wider mb-2 text-sm">Password</label>
            <input 
              type="password" 
              id="password" 
              name="password" 
              required 
              placeholder="••••••••"
              minLength={6}
              className="border-2 border-black p-3 focus:outline-none focus:ring-2 focus:ring-black font-mono" 
            />
          </div>

          {/* Action Button */}
          <button 
            type="submit" 
            className="w-full bg-black text-white font-bold uppercase tracking-widest text-lg p-4 hover:bg-white hover:text-black border-4 border-black transition-colors mt-4"
          >
            Register
          </button>
        </form>

        {/* Footer Links */}
        <div className="mt-8 pt-6 border-t-2 border-black text-center font-mono text-sm">
          <p>Already have an account?</p>
          <Link href="/login" className="font-bold uppercase tracking-widest hover:underline decoration-2 underline-offset-4 mt-2 inline-block">
            Login Here &rarr;
          </Link>
        </div>

      </div>
    </main>
  );
}